version: '3.8'

services:
  herodotnet.api:
    image: ${DOCKER_REGISTRY-}herodotnetapi
    build:
      context: .
      dockerfile: src/HeroDotNet.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HeroDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

  redis:
    image: redis:latest
    container_name: redis-hero
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-hero
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  redis-data:
  sqlserver-data:
